# Generated by Django 2.1.7 on 2019-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author_of_book', models.ManyToManyField(to='core.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='books_written',
            field=models.ManyToManyField(help_text='Enter the info for all of the books this author has written.', to='core.Book'),
        ),
    ]
