# Generated by Django 2.1.7 on 2019-03-11 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 11, 18, 17, 39, 876598, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author_of_book',
            field=models.ManyToManyField(help_text='Enter the name of the person that wrote this book.', to='core.Author'),
        ),
        migrations.AddField(
            model_name='language',
            name='lang_of_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
    ]
