# Generated by Django 2.1.7 on 2019-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190311_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Enter the programming language that this book pertains to.', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_of_book',
            field=models.CharField(max_length=50),
        ),
    ]
