# Generated by Django 2.1.7 on 2019-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190311_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='language_of_book',
        ),
        migrations.AddField(
            model_name='language',
            name='lang',
            field=models.ManyToManyField(help_text='Enter the programming language that this book pertains to.', to='core.Book'),
        ),
    ]
