# Generated by Django 2.1.7 on 2019-03-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_written',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_of_book',
            field=models.ManyToManyField(help_text='Enter the name of the person that wrote this book.', related_name='authors', to='core.Author'),
        ),
    ]
