# Generated by Django 2.1.7 on 2019-03-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190317_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(help_text='Enter the Category of the book.', related_name='category', to='core.Category'),
        ),
    ]
